### ISSUE TITLE
cache_handler setting

### ISSUE THREAD

**Issue by adamwintle** [Adido/mysqlCache#3]
When installing I change the cache_hanlded setting from xPDOFileCache to cache.xPDOMysqlCache; then when I clear the cache the console shows many errors of: 

````Could not load class: xPDOMysqlCache from cache.xpdomysqlcache.````

However, if I change it to just xPDOMysqlCache by removing the prefix cache., it then successfully clears the cache. 

Is this a mistake in the documentation, or a bug in the plugin?

**Comment by markwillis82** [comment]
There was an error with the file resolver that put the cache file within core/xpdo/cache/ - this was causing all the error messages.

When I have the system setting as "cache.xPDOMysqlCache" I get the expected functionality.

I will release the new version tomorrow on modx.com and extras.io

Thank you for finding this and appreciate the support.
