### ISSUE TITLE
Lexicon not refreshing?

### ISSUE THREAD

**Issue by matdave** [Adido/mysqlCache#5]
I am working on building a CMP, but when I have mysqlCaching enabled, it won't clear the lexicon.

**Comment by markwillis82** [comment]
@matdave could you try this update for me:

https://github.com/Adido/mysqlCache/commit/e9877b025818837356de6d80693c16d84238c931

If it works I will bump version and re-release.

**Comment by matdave** [comment]
Okay, it wasn't working for a while, it randomly started giving me the "Couldn't find class" error again.  However, now that we are getting closer to launching, I decided to investigate, and it seems to be working now.
